/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MsgEmergentes;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Somils
 */
public class cambiosHechos extends javax.swing.JPanel {

    /**
     * Creates new form cambiosHechos
     */
    public cambiosHechos() {
        initComponents();
                // Cargar y establecer el GIF en el JLabel existente
     /*   ImageIcon gifIcon = new ImageIcon("/resources/verificado.gif");
        jLabel1.setIcon(gifIcon);
        add(jLabel1, BorderLayout.CENTER);
        jLabel1.revalidate();
        jLabel1.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verificado.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 120, 590, 512);

        jLabel4.setBackground(new java.awt.Color(8, 7, 44));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 7, 44));
        jLabel4.setText("¡Los cambios se han aplicado!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 40, 660, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 670);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
