/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MsgEmergentes;

import java.awt.BorderLayout;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.SwingConstants;
import VisualComponent.LoadingCircle;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Somils
 */
public class MsgLoadNumeric extends javax.swing.JFrame {

    private static AtomicInteger totalAudioFiles = new AtomicInteger();

    /**
     * Creates new form MsgLoadNumeric
     */
    public MsgLoadNumeric() {
        this.totalAudioFiles = totalAudioFiles;
        initComponents();
        setIconImage(getIconImage());

        //  jLabel1.setText("PROCESANDO... "+totalAudioFiles);
        this.setLocationRelativeTo(this);
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(SwingConstants.CENTER);
        LoadingCircle circle = new LoadingCircle();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(circle);
        this.add(jPanel2);
    }

    @Override
    public Image getIconImage() {
        java.net.URL url = ClassLoader.getSystemResource("resources/advertencia.png");
        if (url != null) {
            return Toolkit.getDefaultToolkit().getImage(url);
        } else {
            System.err.println("Resource not found: resources/iconMain.png");
            return null;
        }
    }

    public void updateTotalAudioFiles(int total, int opcion) {
        if (opcion == 0) {
            totalAudioFiles.set(total);
            System.out.println(totalAudioFiles.get());
            jLabel1.setText("PROCESANDO " + totalAudioFiles + " ARCHIVOS DE MUSICA");
            // Aquí puedes actualizar cualquier componente de la UI con el nuevo valor
        } else {
            if (opcion == 1) {

                jLabel1.setText("Finalizando ... ");

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AVISO");
        setMinimumSize(new java.awt.Dimension(330, 110));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(140, 60, 40, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PROCESANDO....");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 330, 60);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SANDY SOFTWARE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 160, 12);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgLoadNumeric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgLoadNumeric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgLoadNumeric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgLoadNumeric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgLoadNumeric().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
